version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3,lambda,logs,sqs,sns,dynamodb,apigateway,events,cloudwatch,kms,eventbridge
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
